template: |
  ##  Release Notes

  $CHANGES

change-template: '- $TITLE - [#$NUMBER]($URL) by @$AUTHOR'
categories:
  - title: ⭐️ Important fixes and improvements
    labels:
      - 'important'
  - title: 💎 Features
    labels:
      - 'feature request :bulb:'
  - title: 🔧 Enhancements
    labels:
      - 'enhancement :wrench:'
  - title: 🔨 Refactoring
    labels:
      - 'refactoring'
  - title: 🐞 Bug fixes
    labels:
      - 'bug :bug:'
  - title: 🚨 Breaking changes
    labels:
      - 'breaking change'
  - title: 🖥️ Frontend
    labels:
      - 'vue'
  - title: 🍃 Spring Boot
    labels:
      - 'spring boot'
  - title: 🪶 Maven
    labels:
      - 'maven'
  - title: 📦 Dependency updates
    label: 'dependencies'
