name: 'run tests'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop]

jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Setup
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'maven'

      # 2. Run tests
      - name: Run Unit & Integration Tests
        run: mvn clean verify --no-transfer-progress
