name: build
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/develop' && github.sha) || github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      skip-ci: ${{ steps.check-ci-skip.outputs.skip_ci }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 'Get the head commit message'
        id: commit-message
        run: |
          head_commit_message=$(git log -1 --no-merges --pretty=%B | tr '\n' ' ' | sed "s/'/'\\\\''/g")
          echo head commit message: $head_commit_message
          echo "message=$head_commit_message" >> $GITHUB_OUTPUT
      - name: 'Prepare commit message and PR title'
        id: prepare-messages
        env:
          COMMIT_MESSAGE: ${{ steps.commit-message.outputs.message }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          commit_message=$(echo "$COMMIT_MESSAGE" | tr -cd '[:alnum:][:space:]\[\]')
          pr_title=$(echo "$PR_TITLE" | tr -d '[:alnum:][:space:]\[\]')
          echo "commit_message=$commit_message" >> $GITHUB_OUTPUT
          echo "pr_title=$pr_title" >> $GITHUB_OUTPUT
      - name: 'Check for ci skip tags'
        id: check-ci-skip
        run: |
          commit_message='${{ steps.prepare-messages.outputs.commit_message }}'
          pr_title='${{ steps.prepare-messages.outputs.pr_title }}'
          skip_tags=('[ci ignore]' '[ignore ci]')

          echo "Checking commit message and pr title for ci skip tags..."
          skip_ci="false"

          for tag in "${skip_tags[@]}"; do
            if [[ "$commit_message" == *"$tag"* ]] || [[ "$pr_title" == *"$tag"* ]]; then
              echo "Found ci skip tag '$tag'."
              echo "skip_ci=true" >> $GITHUB_OUTPUT
              skip_ci="true"
              break
            fi
          done

          if [[ "$skip_ci" == "false" ]]; then
            echo "No ci skip tag found."
            echo "skip_ci=false" >> $GITHUB_OUTPUT
          fi
  tests-windows:
    name: tests-windows
    needs: [setup]
    runs-on: windows-2025
    timeout-minutes: 20
    if: >-
      needs.setup.outputs.skip_ci != 'true'
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v5
      - name: 'Setup: environment'
        id: setup
        uses: ./.github/actions/setup
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Init: install Node.js packages'
        run: npm ci
      - name: 'Test: run backend tests'
        run: |
          ./mvnw clean verify
  tests-linux:
    name: tests-linux
    needs: [setup]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: >-
      needs.setup.outputs.skip_ci != 'true'
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 'Setup: environment'
        id: setup
        uses: ./.github/actions/setup
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml')  }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Init: install Node.js packages'
        run: npm ci
      - name: 'Lint: check'
        run: npm run lint:ci
      - name: 'Test: run backend tests'
        run: |
          chmod +x mvnw
          ./mvnw clean verify
      - name: 'Artifact: upload JAR'
        uses: actions/upload-artifact@v4
        with:
          name: noodle-memories-jar
          path: '${{ github.workspace }}/target/*.jar'
          retention-days: 1
  status-checks:
    name: status-checks
    needs: [tests-linux]
    permissions:
      contents: none
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Validation Status checks'
        run: |
          echo 'Configuration for Status checks that are required'
          echo '${{ toJSON(needs) }}
          if [[ (('skipped' == '${{ needs.tests-linux.result }}') || ('success' == '${{ needs.tests-linux.result }}')) ]]; then
            exit 0
          fi
          exit 1
